export * from "./body-parts.js";
export * from "./body.js";
export * from "./body-factory.js";
export * from "./color-palette.js";
export * from "./fish-body.js";
export * from "./octopus-body.js";
export * from "./snake-body.js";
export * from "./star-body.js";
export * from "./turtle-body.js";
